// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCCjKOfbZYpQFi4SrCTdzFJnXLwrS9YtU',
    appId: '1:84736062319:web:699b46eb54a09b83faae9a',
    messagingSenderId: '84736062319',
    projectId: 'helpher-30b70',
    authDomain: 'helpher-30b70.firebaseapp.com',
    storageBucket: 'helpher-30b70.firebasestorage.app',
    measurementId: 'G-GPHX0MX7P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxaGhgOcKQ84HN2a_KHMgeXZu6Dd44go',
    appId: '1:84736062319:android:ad76082cf8260904faae9a',
    messagingSenderId: '84736062319',
    projectId: 'helpher-30b70',
    storageBucket: 'helpher-30b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATb0OmamtyoVypC8lwqAxnBZhqWVokW5w',
    appId: '1:84736062319:ios:b31c7c1c85b298d8faae9a',
    messagingSenderId: '84736062319',
    projectId: 'helpher-30b70',
    storageBucket: 'helpher-30b70.firebasestorage.app',
    androidClientId: '84736062319-06fin3fv3dnvgr8r6grj3jfjjc1babei.apps.googleusercontent.com',
    iosClientId: '84736062319-va2jh6u51bd2n2ueqqtv9dqicgtg8jks.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATb0OmamtyoVypC8lwqAxnBZhqWVokW5w',
    appId: '1:84736062319:ios:b31c7c1c85b298d8faae9a',
    messagingSenderId: '84736062319',
    projectId: 'helpher-30b70',
    storageBucket: 'helpher-30b70.firebasestorage.app',
    androidClientId: '84736062319-06fin3fv3dnvgr8r6grj3jfjjc1babei.apps.googleusercontent.com',
    iosClientId: '84736062319-va2jh6u51bd2n2ueqqtv9dqicgtg8jks.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpher',
  );

}