name: Deploy Firebase rules

on:
  push:
    branches: [main]
    paths:
      - firestore.rules
      - storage.rules
      - firestore.indexes.json
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Firestore rules, indexes and Storage rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,firestore:indexes,storage
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
